"""The app icons generated by scripts/make_icons.py from assets/icon.svg."""

import re
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
STATIC = ROOT / "src" / "mail_merge" / "web" / "static"


def test_favicon_is_the_master_svg():
    assert (STATIC / "icon.svg").read_bytes() == (ASSETS / "icon.svg").read_bytes()


def test_ico_holds_the_windows_sizes_as_png():
    data = (ASSETS / "MergeMail365.ico").read_bytes()
    reserved, kind, count = struct.unpack_from("<HHH", data)
    assert (reserved, kind) == (0, 1)
    sizes = []
    for i in range(count):
        width, _, _, _, _, _, length, offset = struct.unpack_from("<BBBBHHII", data, 6 + 16 * i)
        assert data[offset:offset + 8] == b"\x89PNG\r\n\x1a\n"
        assert offset + length <= len(data)
        sizes.append(width or 256)
    assert sizes == [16, 24, 32, 48, 64, 128, 256]


def test_icns_holds_every_macos_size():
    data = (ASSETS / "MergeMail365.icns").read_bytes()
    assert data[:4] == b"icns"
    assert struct.unpack_from(">I", data, 4)[0] == len(data)
    types, pos = set(), 8
    while pos < len(data):
        kind, length = struct.unpack_from(">4sI", data, pos)
        types.add(kind.decode("ascii"))
        pos += length
    # 16 to 512 px, each also at 2x (1024 px)
    assert {"ic04", "ic11", "ic05", "ic12", "ic07", "ic13", "ic08", "ic14", "ic09", "ic10"} <= types


def test_build_spec_uses_the_icons():
    spec = (ROOT / "mergemail365.spec").read_text(encoding="utf-8")
    for name in re.findall(r'os\.path\.join\("assets", "([^"]+)"\)', spec):
        assert (ASSETS / name).is_file(), name
    assert "icon=icon_icns" in spec
    assert "icon=icon_ico" in spec
